@TokenRangeGenerator.Api_HostAddress = http://localhost:6000

POST {{TokenRangeGenerator.Api_HostAddress}}/token-range/
Content-Type: application/json
Accept: application/json

{
  "size": 100,
  "requestServerId": "test-server"
}


###
